# Generated by Django 5.2.6 on 2025-09-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('calorias', models.FloatField(help_text='Calorias por 100g')),
                ('proteinas', models.FloatField(help_text='Proteínas por 100g')),
                ('carboidratos', models.FloatField(help_text='Carboidratos por 100g')),
                ('gorduras', models.FloatField(help_text='Gorduras por 100g')),
            ],
        ),
    ]
